# Config file for automatic testing at travis-ci.org

branches:
 only:
  - master

language: python

# Used for testing
env:
  global:
    - EXPECTED_PYTHON_ARCH=64
    - secure: "QJ9EfDYwTlDWh6psKnC1ko5SYvllBlYhoNgc8iLNjj4YcXonJDUEOlnyEIfiw3Y1o6wQm+OsqdIZHjImfSU+7PI3XT3q7rpJyunM0M00Wn6ogRnadc5l9IHOuSlft8OzqOjOS5v9ztYLvf0JNFw3FLEdSypmKXZtQ09334w0TlkIQUlaRg9QX1bSbJd9yEy5fMZ9frFARA04oRKT0fS0aeyeJ6qDO+u1k7Veu5iVeF9r8KqLWbvWigzIurvvlfYKfIjU9f9Lq1HARkWii6hy6jUqJdJmKz1qRlx7jsW0xVrfGcbFvg0NB8fAVY9Rb/VuLPYALjjS/8yWyS+AsvwvzX64XnXVWl9I3puIvdfiu+V5R1ya8F6yK15K5JDMzEWvU3CDxsJNVMj8pXYlag3Bhz3lSwBSDcUC5rdLqDavCaLoe/z8yT4sP0GoG1+bqzy4FwoP9bmniiEolvOfhKXTxssQ7NiuwN4vBtOtvBzPeJ7elJNPF+kNiBR6y06sQUTrDIaqCX5iQuBq1kZKrTa7KPuiK/gGEFx03Z5bhALj4E7L0q0RPKuL9Lpb+jhTcXOm4aNBR7u1V9qQIu0+wjsT3DxEyMkJjMhf9p2Gitswx0OFJVopnWZNaysZJY/ty8FNQLUIb4KsYeMyt2L9rdT9lMyILzbUSmPrfKTsT7mch14="

matrix:
  include:

    - os: linux
      python: "2.7"
      # Used for testing
      env: EXPECTED_PYTHON_VERSION=2.7.14

    - os: osx
      language: generic
      env:
        # Used by pyenv
        - PYTHON_VERSION=3.7.2
        # Used for testing
        - EXPECTED_PYTHON_VERSION=3.7.2

    - os: osx
      language: generic
      env:
        # Used by pyenv
        - PYTHON_VERSION=2.7.15
        # Used for testing
        - EXPECTED_PYTHON_VERSION=2.7.15

cache:
  directories:
    - $HOME/.pyenv/versions/3.7.2
    - $HOME/.pyenv/versions/3.4.8
    - $HOME/.pyenv/versions/2.7.15

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir $HOME/bin; ln -s $(which pip2) $HOME/bin/pip; fi
  - pip install -U scikit-ci
  - ci install

script:
  - ci test

after_success:
  - ci after_test
