version: 2

references:
  ci-steps: &ci-steps
    steps:
      - checkout
      - run:
          name: Initialize Virtual Environment
          command: |
            python -m virtualenv ../venv || python -m venv ../venv
      - run:
          name: Install scikit-ci
          command: |
            . ../venv/bin/activate
            pip install -U scikit-ci
            ci install
      - run:
          name: Run tests
          command: |
            . ../venv/bin/activate
            ci test
      - run:
          name: Deployement
          command: |
            . ../venv/bin/activate
            if [[ "${CIRCLE_BRANCH}" == "master" && "${PRERELEASE_UPLOAD}" == "1" ]]; then
              ci after_test
            fi
      - store_artifacts:
          path: dist/*

jobs:
  python27:
    docker:
      - image: cimg/python:2.7.16
    environment:
      # Used for testing
      - EXPECTED_PYTHON_VERSION: 2.7.16
      - EXPECTED_PYTHON_ARCH: 64
    <<: *ci-steps
  python37:
    docker:
      - image: cimg/python:3.7.12
    environment:
      # Used for testing
      - EXPECTED_PYTHON_VERSION: 3.7.12
      - EXPECTED_PYTHON_ARCH: 64
      # Attempt to upload pre-release only once
      - PRERELEASE_UPLOAD: 1
    <<: *ci-steps

workflows:
  version: 2
  test-package-publish:
    jobs:
      - python27
      - python37
